---
title: "Data Preprocess"
format: html
editor: visual
---

## Load library
```{r}
library(tidyverse)
library(dplyr)
library(countrycode)
```


## Load csv

```{r}
#| label: load-csv

data <- read_csv("average-years-of-schooling-vs-corruption-perception-index.csv")

data
```

## Data Cleanup

```{r}
#| label: filter-data
#| warning: false

filtered_data <- data |>
  filter(Year %in% c(2018),if_all(-Continent, ~ !is.na(.)) | !is.na(Continent)) |>
  mutate(Continent = countrycode::countrycode(Code, "iso3c", "continent"),
         Continent = ifelse(Code == "OWID_KOS", "Europe", Continent))

filtered_data

```


```{r}
#| label: plot-data


ggplot(filtered_data, aes(x = `Corruption Perception Index - Transparency International (2018)`, y = `Learning-Adjusted Years of School`, color = Continent)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Average years of schooling vs Corruption Perception Index",
       x = "Corruption Perception Index - Transparency International (2018)",
       y = "Learning-Adjusted Years of School",
       color = "Continent") +
  theme_minimal()


```


