---
title: "Data Preprocess"
format: html
editor: visual
---

## Load library

```{r}
library(tidyverse)
library(dplyr)
library(countrycode)
library(scales)
library(ggrepel)
```

## Data Preperation

```{r}
#| label: load-csv

data <- read_csv("average-years-of-schooling-vs-corruption-perception-index.csv")

data
```

## Data Cleanup

```{r}
#| label: filter-data
#| warning: false

filtered_data <- data |>
  rename(
    Cpi = `Corruption Perception Index - Transparency International (2018)`,
    Pop = `Population (historical estimates)`,
    Learning_adjusted_yos = `Learning-Adjusted Years of School`
  ) |>
  filter(
    Year %in% c(2018),
    if_all(-Continent, ~ !is.na(.)) | !is.na(Continent),
    Pop > 1e5
  ) |>
  mutate(
    Continent = countrycode::countrycode(Code, "iso3c", "continent"),
    Continent = ifelse(Code == "OWID_KOS", "Europe", Continent),
    Group = case_when( # Assign geographical groups
      Continent %in% c("Asia", "Europe", "Africa") ~ "Afro-Eurasia",
      Continent == "Americas" ~ "Americas",
      Continent == "Oceania" ~ "Oceania",
      TRUE ~ "Unknown" # Catch any unexpected values
    ),
  ) |>
  arrange(desc(Pop))

filtered_data <- mutate(
  filtered_data,
  label = if_else(
    Pop >= 1e8,
    Code,
    ""
  )
)

# Get top 5 countries by population for each group
largest_countries_per_group <- filtered_data |>
  group_by(Group) |>
  arrange(desc(Pop)) |>
  slice_head(n = 5) |>
  summarise(label = Code) 

filtered_data <- filtered_data |>
  mutate(
    label = if_else(
      Code %in% largest_countries_per_group$label,
      Code,
      ""
    )
  )
filtered_data
```

```{r}
#| label: plot-data


ggplot(filtered_data, aes(x = Cpi, y = Learning_adjusted_yos, color = Continent)) +
  geom_point(aes(size = Pop), alpha = 0.6) +
  scale_size_area(
    breaks = 10^(3:12),
    labels = label_number(scale_cut = cut_short_scale()),
    max_size = 15
  ) +
  geom_smooth(
    aes(weight = Pop),
    color = "grey50",
    method = "loess",
    formula = y ~ x
  ) +
  labs(
    title = "Average years of schooling vs Corruption Perception Index",
    x = "Corruption Perception Index - Transparency International (2018)",
    y = "Learning-Adjusted Years of School",
    color = "Continent"
  ) +
  geom_text_repel(aes(label = label, size = 1e6 * Pop^0.2),
    position = position_nudge(x = 0.5, y = 0.5),
    min.segment.length = 0.5,
    max.overlaps = 10,
    show.legend = FALSE,
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 5))) +
  theme_minimal()
```

```{r}
#| label: plot-data-2
#| fig-height: 10
#| fig-width: 10

ggplot(filtered_data, aes(x = Cpi, y = Learning_adjusted_yos, color = Group)) +
  geom_point(aes(size = Pop), alpha = 0.6) +
  geom_jitter(width = 2, height = 0.2) +
  scale_size_area(
    breaks = 10^(6:9),
    labels = label_number(scale_cut = cut_short_scale()),
    max_size = 15
  ) +
  geom_smooth(
    aes(weight = Pop),
    color = "grey50",
    method = "loess",
    formula = y ~ x,
    span = 1
  ) +
  geom_label_repel(aes(x = Cpi + 0.4, y = Learning_adjusted_yos, label = label, size = 1e6 * Pop^0.2),
    min.segment.length = 0.5,
    max.overlaps = 11,
    position = position_nudge(x = 1, y = 0.2),
    show.legend = FALSE,
  ) +
  facet_wrap(~Group, ncol = 1) +
  labs(
    title = "Average years of schooling vs Corruption Perception Index",
    x = "Corruption Perception Index - Transparency International (2018)",
    y = "Learning-Adjusted Years of School",
    color = "Continent"
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 5))) +
  theme_minimal()
```
